### ISSUE TITLE
ubib

### ISSUE THREAD

**Issue by yashhalgaonkar** [niikhilghodke/Insilico-BuildSystem#5]
ivik

**Comment by draeger** [comment]
@yashhalgaonkar: Could you please add some explanation of what that is? I do not understand "ubib" nor "ivik".

**Comment by yashhalgaonkar** [comment]
Prof,
Nikhil Ghodke  was taking a workshop on Git and GitHub. And while taking
the workshop , he explained about issues in GitHub. Sir been new to GitHub
just wanted to experiment with GitHub and by mistake open up that issue.
There is no issue which I can spot in the project.
Regards,
Yash Halgaonkar.

**Comment by draeger** [comment]
Ok, thanks for the explanation!
